language: node_js
node_js:
  - "9"
  - "8"
  - "7"
  - "6"
  - "5"
  - "4"
  - "0.12"
  - "0.10"
sudo: required
dist: trusty
allow_failures:
  node_js:
    - "7"
    - "5"
    - "0.12"
    - "0.10"
addons:
  postgresql: 9.3
env: PGCONFIG='pg://postgres@localhost/nopg_test' DISABLE_NEWRELIC=yes DEBUG_NOPG=true NOPG_TIMEOUT=2000
before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -qq postgresql-9.3-plv8
  - psql template1 -c 'CREATE EXTENSION plv8;' -U postgres
  - psql template1 -c 'CREATE EXTENSION "uuid-ossp";' -U postgres
  - psql template1 -c 'CREATE EXTENSION tcn;' -U postgres
  - psql template1 -c 'CREATE EXTENSION moddatetime;' -U postgres
  - psql -c 'CREATE DATABASE nopg_test;' -U postgres
  - ./src/bin/nopg.js -v init
after_failure:
  - psql -c '\d' -U postgres
  - sudo cat /var/log/postgresql/postgresql-9.3-main.log
